name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: EnniBr
          gif_out_path: ./github-contribution-grid-snake.gif
          svg_out_path: ./github-contribution-grid-snake.svg

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: .
