name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Snake Game
        uses: Platane/snk@master
        with:
          github_user_name: EnniBr
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif
          dark_snake: true  # Habilita versão dark

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ GH_PAT }}
          publish_dir: ./dist
          destination_dir: ./output
          publish_branch: output
          keep_files: true
